论文： A national longitudinal dataset of skills taught in U.S. higher education curricula  
链接： https://arxiv.org/abs/2404.13163   
数据链接： https://figshare.com/articles/dataset/A_national_longitudinal_dataset_of_skills_taught_in_U_S_higher_education_curricula/25632429

名词记录  

course descriptions detailed workplace activities (DWAs)

Department of Labor (DOL)

In [1]:
!du -ms *

17640	25632429.zip
80	abilities_scores.gzip
1412	detailed_work_activities_scores.gzip
2	load_datasets.ipynb
3	syllabi.gzip
16146	tasks_scores.gzip

文件对应：

- syllabi.gzip: 281153份 课程大纲简要信息， 年份、学科领域、学校等
- abilities_scores.gzip： 每一份 enduring abilities, 大概52种的评分
- detailed_work_activities_scores.gzip：  2,000种 detailed descriptions of work activities 的评分
- tasks_scores.gzip： 18000种任务能力的评分，  Task is a basic unit of work

# 课程大纲 简要

In [2]:
import pandas as pd

file_path= './syllabi.gzip'
df1 = pd.read_csv(file_path, compression='gzip')

In [3]:
df1.columns

Index(['id', 'year', 'field_name', 'institution_name', 'UnitID', 'state_code',
       'city', 'syllabi_cnt', 'syllabi_probability'],
      dtype='object')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281153 entries, 0 to 281152
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   id                   281153 non-null  int64
 1   year                 281153 non-null  int64
 2   field_name           281153 non-null  object
 3   institution_name     281153 non-null  object
 4   UnitID               281153 non-null  int64
 5   state_code           281153 non-null  object
 6   city                 281153 non-null  object
 7   syllabi_cnt          281153 non-null  int64
 8   syllabi_probability  281153 non-null  float64
dtypes: float64(1), int64(4), object(4)
memory usage: 19.3+ MB

In [5]:
df1[['field_name']]

                field_name
0                 Medicine
1             Basic Skills
2                 Business
3       English Literature
4       English Literature
...                    ...
281148     Women's Studies
281149     Women's Studies
281150     Women's Studies
281151     Women's Studies
281152     Women's Studies

[281153 rows x 1 columns]

In [6]:
df1[df1.field_name == 'Computer Science']

,id,year,field_name,institution_name,UnitID,state_code,city,syllabi_cnt,syllabi_probability
11,100011,2003,Computer Science,Illinois Central College,145682,IL,East Peoria,1,0.9360
36,100036,2002,Computer Science,Lake Superior State University,170639,MI,Sault Ste. Marie,1,0.9910
37,100037,2004,Computer Science,Lake Superior State University,170639,MI,Sault Ste. Marie,1,0.9970
172,100172,2000,Computer Science,William Paterson University,187444,NJ,Wayne,1,0.9780
173,100173,2001,Computer Science,William Paterson University,187444,NJ,Wayne,1,0.9624
...,...,...,...,...,...,...,...,...,...
280786,380786,2013,Computer Science,Windward Community College,141990,HI,Kāne‘ohe,7,0.9614
280787,380787,2014,Computer Science,Windward Community College,141990,HI,Kāne‘ohe,12,0.8200
280788,380788,2015,Computer Science,Windward Community College,141990,HI,Kāne‘ohe,12,0.8154
280789,380789,2016,Computer Science,Windward Community College,141990,HI,Kāne‘ohe,11,0.8794
280790,380790,2017,Computer Science,Windward Community College,141990,HI,Kāne‘ohe,27,0.8380

In [7]:
cs_idx = 11

# 将 O*NET DWAs to Abilities 数据

In [8]:
file_path= './abilities_scores.gzip'
df2 = pd.read_csv(file_path, compression='gzip')

In [9]:
df2.columns

Index(['id', 'Selective Attention', 'Time Sharing', 'Category Flexibility',
       'Deductive Reasoning', 'Fluency of Ideas', 'Inductive Reasoning',
       'Information Ordering', 'Originality', 'Problem Sensitivity',
       'Memorization', 'Flexibility of Closure', 'Perceptual Speed',
       'Speed of Closure', 'Mathematical Reasoning', 'Number Facility',
       'Spatial Orientation', 'Visualization', 'Oral Comprehension',
       'Oral Expression', 'Written Comprehension', 'Written Expression',
       'Stamina', 'Dynamic Flexibility', 'Extent Flexibility',
       'Gross Body Coordination', 'Gross Body Equilibrium', 'Dynamic Strength',
       'Explosive Strength', 'Static Strength', 'Trunk Strength',
       'Control Precision', 'Multilimb Coordination', 'Rate Control',
       'Response Orientation', 'Arm-Hand Steadiness', 'Finger Dexterity',
       'Manual Dexterity', 'Reaction Time', 'Speed of Limb Movement',
       'Wrist-Finger Speed', 'Auditory Attention', 'Hearing Sensitivity',
       'Sound Localization', 'Speech Clarity', 'Speech Recognition',
       'Depth Perception', 'Far Vision', 'Glare Sensitivity', 'Near Vision',
       'Night Vision', 'Peripheral Vision', 'Visual Color Discrimination'],
      dtype='object')

In [10]:
len(df2.columns)

53

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281153 entries, 0 to 281152
Data columns (total 53 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           281153 non-null  int64
 1   Selective Attention          281153 non-null  float64
 2   Time Sharing                 281153 non-null  float64
 3   Category Flexibility         281153 non-null  float64
 4   Deductive Reasoning          281153 non-null  float64
 5   Fluency of Ideas             281153 non-null  float64
 6   Inductive Reasoning          281153 non-null  float64
 7   Information Ordering         281153 non-null  float64
 8   Originality                  281153 non-null  float64
 9   Problem Sensitivity          281153 non-null  float64
 10  Memorization                 281153 non-null  float64
 11  Flexibility of Closure       281153 non-null  float64
 12  Perceptual Speed             281153 non-null  float64
 13  Speed of Closure             281153 non-null  float64
 14  Mathematical Reasoning       281153 non-null  float64
 15  Number Facility              281153 non-null  float64
 16  Spatial Orientation          281153 non-null  float64
 17  Visualization                281153 non-null  float64
 18  Oral Comprehension           281153 non-null  float64
 19  Oral Expression              281153 non-null  float64
 20  Written Comprehension        281153 non-null  float64
 21  Written Expression           281153 non-null  float64
 22  Stamina                      281153 non-null  float64
 23  Dynamic Flexibility          281153 non-null  float64
 24  Extent Flexibility           281153 non-null  float64
 25  Gross Body Coordination      281153 non-null  float64
 26  Gross Body Equilibrium       281153 non-null  float64
 27  Dynamic Strength             281153 non-null  float64
 28  Explosive Strength           281153 non-null  float64
 29  Static Strength              281153 non-null  float64
 30  Trunk Strength               281153 non-null  float64
 31  Control Precision            281153 non-null  float64
 32  Multilimb Coordination       281153 non-null  float64
 33  Rate Control                 281153 non-null  float64
 34  Response Orientation         281153 non-null  float64
 35  Arm-Hand Steadiness          281153 non-null  float64
 36  Finger Dexterity             281153 non-null  float64
 37  Manual Dexterity             281153 non-null  float64
 38  Reaction Time                281153 non-null  float64
 39  Speed of Limb Movement       281153 non-null  float64
 40  Wrist-Finger Speed           281153 non-null  float64
 41  Auditory Attention           281153 non-null  float64
 42  Hearing Sensitivity          281153 non-null  float64
 43  Sound Localization           281153 non-null  float64
 44  Speech Clarity               281153 non-null  float64
 45  Speech Recognition           281153 non-null  float64
 46  Depth Perception             281153 non-null  float64
 47  Far Vision                   281153 non-null  float64
 48  Glare Sensitivity            281153 non-null  float64
 49  Near Vision                  281153 non-null  float64
 50  Night Vision                 281153 non-null  float64
 51  Peripheral Vision            281153 non-null  float64
 52  Visual Color Discrimination  281153 non-null  float64
dtypes: float64(52), int64(1)
memory usage: 113.7 MB


    Selective Attention - 选择性注意
    Time Sharing - 时间共享
    Category Flexibility - 类别灵活性
    Deductive Reasoning - 演绎推理
    Fluency of Ideas - 思维流畅性
    Inductive Reasoning - 归纳推理
    Information Ordering - 信息排序
    Originality - 创造性
    Problem Sensitivity - 问题敏感性
    Memorization - 记忆
    Flexibility of Closure - 结束灵活性
    Perceptual Speed - 感知速度
    Speed of Closure - 结束速度
    Mathematical Reasoning - 数学推理
    Number Facility - 数字能力
    Spatial Orientation - 空间定位
    Visualization - 可视化
    Oral Comprehension - 口头理解
    Oral Expression - 口头表达
    Written Comprehension - 书面理解
    Written Expression - 书面表达
    Stamina - 耐力
    Dynamic Flexibility - 动态灵活性
    Extent Flexibility - 范围灵活性
    Gross Body Coordination - 大体协调性
    Gross Body Equilibrium - 大体平衡
    Dynamic Strength - 动态力量
    Explosive Strength - 爆发力
    Static Strength - 静态力量
    Trunk Strength - 躯干力量
    Control Precision - 控制精度
    Multilimb Coordination - 多肢协调
    Rate Control - 速率控制
    Response Orientation - 反应取向
    Arm-Hand Steadiness - 手臂-手稳定性
    Finger Dexterity - 手指灵活性
    Manual Dexterity - 手部灵活性
    Reaction Time - 反应时间
    Speed of Limb Movement - 肢体移动速度
    Wrist-Finger Speed - 腕部-手指速度
    Auditory Attention - 听觉注意力
    Hearing Sensitivity - 听觉敏感度
    Sound Localization - 声音定位
    Speech Clarity - 语音清晰度
    Speech Recognition - 语音识别
    Depth Perception - 深度感知
    Far Vision - 远视
    Glare Sensitivity - 眩光敏感性
    Near Vision - 近视
    Night Vision - 夜视
    Peripheral Vision - 周边视觉
    Visual Color Discrimination - 视觉颜色辨别

# DWA score

4 Top 10 Detailed Work Activities (DWA) per Field of Study (FOS)

In [12]:
# file_path= './detailed_work_activities_scores.gzip'
# df3 = pd.read_csv(file_path, compression='gzip')

filename = './detailed_work_activities_scores.gzip'
for chunk in pd.read_csv(filename, compression='gzip', chunksize = 1000):
    columns = chunk.columns
    df3 = chunk
    break

In [13]:
len(df3.columns)

2071

In [14]:
df3[3:5]

,id,Review art or design materials.,Study details of musical compositions.,Review production information to determine costume or makeup requirements.,Study scripts to determine project requirements.,Read materials to determine needed actions.,Read maps to determine routes.,Review customer information.,Read work orders or other instructions to determine product specifications or materials requirements.,Read technical information needed to perform maintenance or repairs.,...,Acquire supplies or equipment.,Prescribe treatments or therapies.,Control prescription refills or authorizations.,Prescribe medications.,Prescribe assistive medical devices or related treatments.,Monitor availability of equipment or supplies.,Inventory materials or equipment.,Inventory medical supplies or equipment.,Monitor inventories of products or materials.,Monitor resources.
3,100003,0.3909,0.381000,0.239700,0.455600,0.445300,0.281000,0.287400,0.302500,0.266400,...,0.279800,0.164600,0.154500,0.140400,0.169100,0.236200,0.2374,0.240000,0.267000,0.229700
4,100004,0.2999,0.352586,0.289243,0.438029,0.442086,0.269114,0.270257,0.228714,0.257471,...,0.196457,0.168703,0.157221,0.127176,0.168874,0.259586,0.2038,0.218929,0.255743,0.233643

In [15]:
df3.iloc[cs_idx]

id                                                                            100011.0000
Review art or design materials.                                                    0.4010
Study details of musical compositions.                                             0.2622
Review production information to determine costume or makeup requirements.         0.3125
Study scripts to determine project requirements.                                   0.4436
                                                                                 ...
Monitor availability of equipment or supplies.                                     0.3364
Inventory materials or equipment.                                                  0.3389
Inventory medical supplies or equipment.                                           0.3370
Monitor inventories of products or materials.                                      0.3132
Monitor resources.                                                                 0.3066
Name: 11, Length: 2071, dtype: float64

In [17]:
print(list(df3.columns)[:100])

['id', 'Review art or design materials.', 'Study details of musical compositions.', 'Review production information to determine costume or makeup requirements.', 'Study scripts to determine project requirements.', 'Read materials to determine needed actions.', 'Read maps to determine routes.', 'Review customer information.', 'Read work orders or other instructions to determine product specifications or materials requirements.', 'Read technical information needed to perform maintenance or repairs.', 'Study blueprints or other instructions to determine equipment setup requirements.', 'Read documents to gather technical information.', 'Review technical documents to plan work.', 'Review blueprints or specifications to determine work requirements.', 'Review work orders or schedules to determine operations or procedures.', 'Review blueprints or other instructions to determine operational methods or sequences.', 'Evaluate reports or designs to determine work needs.', 'Read work orders or descriptions of problems to determine repairs or modifications needed.', 'Interpret blueprints, specifications, or diagrams to inform installation, development or operation activities.', 'Review details of technical drawings or specifications.', 'Read work orders to determine material or setup requirements.', 'Collect evidence for legal proceedings.', 'Examine crime scenes to obtain evidence.', 'Investigate crimes committed within organizations.', 'Investigate legal issues.', 'Examine records or other types of data to investigate criminal activities.', 'Conduct hearings to investigate legal issues.', 'Investigate illegal or suspicious activities.', 'Obtain property information.', 'Use databases to locate investigation details or other information.', 'Search information sources to find specific data.', 'Gather financial records.', 'Retrieve information from electronic sources.', 'Gather information in order to provide services to clients.', 'Search files, databases or reference materials to obtain needed information.', 'Collect archival data.', 'Evaluate information related to legal matters in public or personal records.', 'Research relevant legal materials to aid decision making.', 'Gather organizational performance information.', 'Gather information about work conditions or locations.', 'Gather physical survey data.', 'Collect data about project sites.', 'Obtain information about goods or services.', 'Research hydrologic features or processes.', 'Research geological features or processes.', 'Conduct climatological research.', 'Conduct surveys in organizations.', 'Research industrial processes or operations.', 'Conduct scientific research of organizational behavior or processes.', 'Research impacts of environmental conservation initiatives.', 'Research issues related to the environment or sustainable business practices.', 'Investigate the environmental impact of projects.', 'Monitor environmental impacts of production or development activities.', 'Research environmental impact of industrial or development activities.', 'Identify environmental concerns.', 'Evaluate environmental impact of operational or development activities.', 'Gather information for news stories.', 'Gather medical information from patient histories.', 'Collect medical information from patients, family members, or other medical professionals.', 'Collect information from people through observation, interviews, or surveys.', 'Collect information about clients.', 'Research livestock management methods.', 'Research crop management methods.', 'Research sustainable agricultural processes or practices.', 'Conduct market research.', 'Gather customer or product information to determine customer needs.', 'Obtain personal or financial information about customers or applicants.', 'Conduct opinion surveys or needs assessments.', 'Collect data about customer needs.', "Observe individuals' activities to gather information or compile evidence.", 'Investigate personal characteristics or activities of individuals.', 'Research genetic characteristics or expression.', 'Research diseases or parasites.', 'Conduct research of processes in natural or industrial ecosystems.', 'Research microbiological or chemical processes or structures.', 'Classify organisms based on their characteristics or behavior.', 'Examine characteristics or behavior of living organisms.', 'Obtain documentation to authorize activities.', 'Obtain copyrights or other legal permissions.', 'Obtain written authorization to perform activities.', 'Conduct anthropological or archaeological research.', 'Conduct historical research.', 'Conduct research on social issues.', 'Research social issues.', 'Conduct research to increase knowledge about medical issues.', 'Collect information about community health needs.', 'Research engineering aspects of biological or chemical processes.', 'Research engineering applications of emerging technologies.', 'Research design or application of green technologies.', 'Conduct research to gain information about products or processes.', 'Research advanced engineering designs or applications.', 'Research energy production, use, or conservation.', 'Research human performance or health factors related to engineering or design activities.', 'Research new technologies.', 'Research product safety.', 'Research methods to improve food products.', 'Investigate accidents to determine causes.', 'Examine debris to obtain information about causes of fires.', 'Investigate transportation incidents, violations, or complaints.', 'Investigate industrial or transportation accidents.']

In [18]:
df3.iloc[cs_idx][['Develop specifications for computer network operation.', 
                  'Design software applications.', 
                  'Develop models of information or communications systems.']]

Develop specifications for computer network operation.      0.465
Design software applications.                               0.350
Develop models of information or communications systems.    0.348
Name: 11, dtype: float64

# task scores

Task Statement (Task): Finally, a Task is a basic unit of work, the smallest action that constitutes part of a job.
Roughly 18,000 Tasks provide the most detailed overview of the job responsibilities

https://www.onetcenter.org/dictionary/20.1/excel/task_statements.html (accessed on 5th February 2024).

In [20]:
filename = './tasks_scores.gzip'
for chunk in pd.read_csv(filename, compression='gzip', chunksize = 10):
    columns = chunk.columns
    df = chunk
    print(list(chunk.columns)[:100])
    print(len(list(chunk.columns)))
    break

['id', 'Resolve customer complaints regarding sales and service.', 'Monitor customer preferences to determine focus of sales efforts.', 'Determine price schedules and discount rates.', 'Review operational records and reports to project sales and determine profitability.', 'Confer or consult with department heads to plan advertising services and to secure information on equipment and customer specifications.', 'Advise dealers and distributors on policies and operating procedures to ensure functional effectiveness of business.', 'Prepare budgets and approve budget expenditures.', 'Represent company at trade association meetings to promote products.', 'Plan and direct staffing, training, and performance evaluations to develop and control sales and service programs.', 'Visit franchised dealers to stimulate interest in establishment or expansion of leasing programs.', 'Oversee regional and local sales managers and their staffs.', 'Direct clerical staff to keep records of export correspondence, bid requests, and credit collections, and to maintain current information on tariffs, licenses, and restrictions.', 'Direct foreign sales and service outlets of an organization.', 'Assess marketing potential of new and existing store locations, considering statistics and expenditures.', 'Direct or coordinate the supportive services department of a business, agency, or organization.', 'Set goals and deadlines for the department.', 'Prepare and review operational reports and schedules to ensure accuracy and efficiency.', 'Analyze internal processes and recommend and implement procedural or policy changes to improve operations, such as supply changes or the disposal of records.', 'Acquire, distribute and store supplies.', 'Plan, administer, and control budgets for contracts, equipment, and supplies.', 'Hire and terminate clerical and administrative personnel.', 'Conduct classes to teach procedures to staff.', 'Direct or coordinate production, processing, distribution, or marketing activities of industrial organizations.', 'Develop budgets or approve expenditures for supplies, materials, or human resources, ensuring that materials, labor, or equipment are used efficiently to meet production targets.', 'Review processing schedules or production orders to make decisions concerning inventory requirements, staffing requirements, work procedures, or duty assignments, considering budgetary limitations and time constraints.', 'Review operations and confer with technical or administrative staff to resolve production or processing problems.', 'Hire, train, evaluate, or discharge staff or resolve personnel grievances.', 'Initiate or coordinate inventory or cost control programs.', 'Prepare and maintain production reports or personnel records.', 'Set and monitor product standards, examining samples of raw products or directing testing during processing, to ensure finished products are of prescribed quality.', 'Develop or implement production tracking or quality control systems, analyzing production, quality control, maintenance, or other operational reports to detect production problems.', 'Review plans and confer with research or support staff to develop new products or processes.', 'Coordinate or recommend procedures for facility or equipment maintenance or modification, including the replacement of machines.', 'Maintain current knowledge of the quality control field, relying on current literature pertaining to materials use, technological advances, or statistical studies.', 'Negotiate materials prices with suppliers.', 'Direct, supervise and evaluate work activities of medical, nursing, technical, clerical, service, maintenance, and other personnel.', 'Establish objectives and evaluative or operational criteria for units managed.', 'Direct or conduct recruitment, hiring, and training of personnel.', 'Develop and maintain computerized record management systems to store and process data, such as personnel activities and information, and to produce reports.', 'Develop and implement organizational policies and procedures for the facility or medical unit.', 'Conduct and administer fiscal operations, including accounting, planning budgets, authorizing expenditures, establishing rates for services, and coordinating financial reporting.', 'Establish work schedules and assignments for staff, according to workload, space, and equipment availability.', 'Maintain communication between governing boards, medical staff, and department heads by attending board meetings and coordinating interdepartmental functioning.', 'Monitor the use of diagnostic services, inpatient beds, facilities, and staff to ensure effective use of resources and assess the need for additional staff, equipment, and services.', 'Maintain awareness of advances in medicine, computerized diagnostic and treatment equipment, data processing technology, government regulations, health insurance changes, and financing options.', 'Manage change in integrated health care delivery systems, such as work restructuring, technological innovations, and shifts in the focus of care.', 'Prepare activity reports to inform management of the status and implementation plans of programs, services, and quality initiatives.', 'Plan, implement, and administer programs and services in a health care or medical facility, including personnel administration, training, and coordination of medical, nursing and physical plant staff.', 'Consult with medical, business, and community groups to discuss service problems, respond to community needs, enhance public relations, coordinate activities and plans, and promote health programs.', 'Inspect facilities and recommend building or equipment modifications to ensure emergency readiness and compliance to access, safety, and sanitation regulations.', 'Review and analyze facility activities and data to aid planning and cash and risk management and to improve service utilization.', 'Develop or expand and implement medical programs or health services that promote research, rehabilitation, and community health.', 'Develop instructional materials and conduct in-service and community-based educational programs.', 'Monitor and analyze sales records, trends, or economic conditions to anticipate consumer buying patterns, company sales, and needed inventory.', 'Authorize payment of invoices or return of merchandise.', 'Consult with store or merchandise managers about budgets or goods to be purchased.', 'Train or supervise sales or clerical staff.', 'Provide clerks with information to print on price tags, such as price, mark-ups or mark-downs, manufacturer number, season code, or style number.', 'Determine which products should be featured in advertising, the advertising medium to be used, or when the ads should be run.', "Monitor competitors' sales activities by following their advertisements in newspapers or other media.", 'Analyze blueprints and other documentation to prepare time, cost, materials, and labor estimates.', 'Assess cost effectiveness of products, projects or services, tracking actual costs relative to bids as the project develops.', 'Consult with clients, vendors, personnel in other departments, or construction foremen to discuss and formulate estimates and resolve issues.', 'Confer with engineers, architects, owners, contractors, and subcontractors on changes and adjustments to cost estimates.', 'Prepare estimates used by management for purposes such as planning, organizing, and scheduling work.', 'Prepare estimates for use in selecting vendors or subcontractors.', 'Review material and labor requirements to decide whether it is more cost-effective to produce or purchase components.', 'Prepare cost and expenditure statements and other necessary documentation at regular intervals for the duration of the project.', 'Prepare and maintain a directory of suppliers, contractors and subcontractors.', 'Set up cost monitoring and reporting systems and procedures.', 'Establish and maintain tendering process, and conduct negotiations.', 'Conduct special studies to develop and establish standard hour and related cost data or to reduce cost.', 'Visit site and record information about access, drainage and topography, and availability of utility services.', 'Keep up with developments in area of expertise by reading current journals, books, or magazine articles.', 'Present information with a variety of instructional techniques or formats, such as role playing, simulations, team exercises, group discussions, videos, or lectures.', 'Schedule classes based on availability of classrooms, equipment, or instructors.', 'Offer specific training programs to help workers maintain or improve job skills.', 'Monitor, evaluate, or record training activities or program effectiveness.', 'Attend meetings or seminars to obtain information for use in training programs or to inform management of training program status.', 'Coordinate recruitment and placement of training program participants.', 'Evaluate training materials prepared by instructors, such as outlines, text, or handouts.', 'Develop alternative training methods if expected improvements are not seen.', 'Assess training needs through surveys, interviews with employees, focus groups, or consultation with managers, instructors, or customer representatives.', 'Select and assign instructors to conduct training.', 'Devise programs to develop executive potential among employees in lower-level positions.', 'Negotiate contracts with clients for desired training outcomes, fees, or expenses.', 'Refer trainees to employer relations representatives, to locations offering job placement assistance, or to appropriate social services agencies, if warranted.', 'Prepare information regarding design, structure specifications, materials, color, equipment, estimated costs, or construction time.', 'Consult with clients to determine functional or spatial requirements of structures.', 'Prepare contract documents for building contractors.', 'Integrate engineering elements into unified architectural designs.', 'Administer construction contracts.', 'Represent clients in obtaining bids or awarding construction contracts.', 'Prepare operating and maintenance manuals, studies, or reports.', 'Compute load and grade requirements, water flow rates, or material stress factors to determine design specifications.', 'Inspect project sites to monitor progress and ensure conformance to design specifications and safety or sanitation standards.', 'Direct or participate in surveying to lay out installations or establish reference points, grades, or elevations to guide construction.', 'Estimate quantities and cost of materials, equipment, or labor to determine project feasibility.', 'Prepare or present public reports on topics such as bid proposals, deeds, environmental impact statements, or property and right-of-way descriptions.']
17993

In [21]:
len(columns)

17993

In [22]:
for i in range(1, len(columns), 20):
    chunk[columns[i:i+20]].info()
    break

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 20 columns):
 #   Column                                                                                                                                                                             Non-Null Count  Dtype
---  ------                                                                                                                                                                             --------------  -----
 0   Resolve customer complaints regarding sales and service.                                                                                                                           10 non-null     float64
 1   Monitor customer preferences to determine focus of sales efforts.                                                                                                                  10 non-null     float64
 2   Determine price schedules and discount rates.                                                                                                                                      10 non-null     float64
 3   Review operational records and reports to project sales and determine profitability.                                                                                               10 non-null     float64
 4   Confer or consult with department heads to plan advertising services and to secure information on equipment and customer specifications.                                           10 non-null     float64
 5   Advise dealers and distributors on policies and operating procedures to ensure functional effectiveness of business.                                                               10 non-null     float64
 6   Prepare budgets and approve budget expenditures.                                                                                                                                   10 non-null     float64
 7   Represent company at trade association meetings to promote products.                                                                                                               10 non-null     float64
 8   Plan and direct staffing, training, and performance evaluations to develop and control sales and service programs.                                                                 10 non-null     float64
 9   Visit franchised dealers to stimulate interest in establishment or expansion of leasing programs.                                                                                  10 non-null     float64
 10  Oversee regional and local sales managers and their staffs.                                                                                                                        10 non-null     float64
 11  Direct clerical staff to keep records of export correspondence, bid requests, and credit collections, and to maintain current information on tariffs, licenses, and restrictions.  10 non-null     float64
 12  Direct foreign sales and service outlets of an organization.                                                                                                                       10 non-null     float64
 13  Assess marketing potential of new and existing store locations, considering statistics and expenditures.                                                                           10 non-null     float64
 14  Direct or coordinate the supportive services department of a business, agency, or organization.                                                                                    10 non-null     float64
 15  Set goals and deadlines for the department.                                                                                                                                        10 non-null     float64
 16  Prepare and review operational reports and schedules to ensure accuracy and efficiency.                                                                                            10 non-null     float64
 17  Analyze internal processes and recommend and implement procedural or policy changes to improve operations, such as supply changes or the disposal of records.                      10 non-null     float64
 18  Acquire, distribute and store supplies.                                                                                                                                            10 non-null     float64
 19  Plan, administer, and control budgets for contracts, equipment, and supplies.                                                                                                      10 non-null     float64
dtypes: float64(20)
memory usage: 1.7 KB